version: "3.8"

x-service-volume: &service-volumes
    - ./:/app/:rw,cached

services:
    website:
        image: djangotest_website_test:latest
        command: python manage.py runserver 0.0.0.0:8000
        volumes: *service-volumes
        depends_on: 
            - db_migrate
        ports: 
            - "8000:8000"

    db_migrate:
        image: djangotest_website_test:latest
        command: python manage.py migrate
        volumes: *service-volumes
